package com.lm.bos.domain;
// Generated 2016-12-21 14:58:41 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AuthFunction generated by hbm2java
 */
public class AuthFunction implements java.io.Serializable {

	private String id;
	private AuthFunction authFunction;
	private String name;
	private String code;
	private String description;
	private String page;
	private String generatemenu;
	private Integer zindex;
	private Set authFunctions = new HashSet(0);
	private Set authRoles = new HashSet(0);

	public AuthFunction() {
	}

	public AuthFunction(String id) {
		this.id = id;
	}

	public AuthFunction(String id, AuthFunction authFunction, String name, String code, String description, String page,
			String generatemenu, Integer zindex, Set authFunctions, Set authRoles) {
		this.id = id;
		this.authFunction = authFunction;
		this.name = name;
		this.code = code;
		this.description = description;
		this.page = page;
		this.generatemenu = generatemenu;
		this.zindex = zindex;
		this.authFunctions = authFunctions;
		this.authRoles = authRoles;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public AuthFunction getAuthFunction() {
		return this.authFunction;
	}

	public void setAuthFunction(AuthFunction authFunction) {
		this.authFunction = authFunction;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPage() {
		return this.page;
	}

	public void setPage(String page) {
		this.page = page;
	}

	public String getGeneratemenu() {
		return this.generatemenu;
	}

	public void setGeneratemenu(String generatemenu) {
		this.generatemenu = generatemenu;
	}

	public Integer getZindex() {
		return this.zindex;
	}

	public void setZindex(Integer zindex) {
		this.zindex = zindex;
	}

	public Set getAuthFunctions() {
		return this.authFunctions;
	}

	public void setAuthFunctions(Set authFunctions) {
		this.authFunctions = authFunctions;
	}

	public Set getAuthRoles() {
		return this.authRoles;
	}

	public void setAuthRoles(Set authRoles) {
		this.authRoles = authRoles;
	}

}
