package com.lm.bos.domain;
// Generated 2016-12-21 14:58:41 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AuthRole generated by hbm2java
 */
public class AuthRole implements java.io.Serializable {

	private String id;
	private String name;
	private String code;
	private String description;
	private Set authFunctions = new HashSet(0);
	private Set users = new HashSet(0);

	public AuthRole() {
	}

	public AuthRole(String id) {
		this.id = id;
	}

	public AuthRole(String id, String name, String code, String description, Set authFunctions, Set users) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.description = description;
		this.authFunctions = authFunctions;
		this.users = users;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getAuthFunctions() {
		return this.authFunctions;
	}

	public void setAuthFunctions(Set authFunctions) {
		this.authFunctions = authFunctions;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
